#ifndef JHP_JHPEOPLE_RESIDS_HPP
#define JHP_JHPEOPLE_RESIDS_HPP


// !max value is type short max (32767)
#define JHP_JHPEOPLE_ABOUT_STRINGSID	32000
#define JHP_JHPEOPLE_MENU_STRINGSID		32500
#define JHP_JHPEOPLE_MENU_ICONID		32501

#endif // JHP_JHPEOPLE_RESIDS_HPP

